filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage ./tests/'
                coverage:
                    file: 'coverage'
                    format: 'clover'